<?php
/**
 * We will be using Drupal's mail API in this file.
 */

use Drupal\Component\Utility\SafeMarkup;

/**
 * Implementation of hook_mail().
 */
function aca_email_mail($key, $message, $params) {
  // Get language code, which provides current user language.
  $options = array(
    'langcode' => $message['langcode'],
  );
  
  // configuring the message
  switch ($key) {
    case 'contact_message':
	  $from = \Drupal::config('system.site')->get('mail');
	  $message['subject'] = t('E-mail sent to you from @sender', array ( '@sender' => $from ), $options);
	  $message['body'][] = t('We sent you the following message: ', $options);
	  // We need to translate HTML to text before sending message, so this function removes HTML tags from the message text.
	  $message['body'][] = SafeMarkup::checkPlain($params['message']);
	  break;
  }
}

// function aca_email_mail($key, $message, $params) {
//   $data['user'] = $params['account'];
//   $options['langcode'] = $message['langcode'];
//   // user_mail_tokens($variables, $data, $options);
//   switch($key) {
//     case 'notice':
//       // If the recipient can receive such notices by instant-message, do
//       // not send by email.
//       if (example_im_send($key, $message, $params)) {
//         $message['send'] = FALSE;
//         break;
//       }
//       $message['subject'] = t('Notification from @site', $params['account'], $options);
//       $message['body'][] = t("Dear @username\n\nThere is new content available on the site.", $variables, $options);
//       break;
//   }
// }

/**
 * Implements hook_mail_alter().
 * 
 * Not yet implemented, this function need to call getGeocode() method in order to alter the message.
 */
function aca_email_alter(&$message) {
  //$options = array(
  //  'langcode' => $message['langcode'],
  //);
  // Does nothing, for now...
}
?>